=== websealevel/doc-phpxml/data.dtd
<!ELEMENT theme_official_plugins (theme*) >
<!ELEMENT theme (plugin*)>
<!ATTLIST theme_official_plugins xmlns CDATA #REQUIRED >
<!ATTLIST theme name CDATA #REQUIRED >
<!ELEMENT plugin (name,label,path,description,official_link) >
<!ELEMENT name (#PCDATA) >
<!ELEMENT label (#PCDATA) >
<!ELEMENT path (#PCDATA) >
<!ELEMENT description (#PCDATA) >
<!ELEMENT official_link (#PCDATA) >

=== websealevel/doc-phpxml/data.xml
<?xml version='1.0' encoding='UTF-8'  standalone = "no"?>
<!DOCTYPE theme_official_plugins SYSTEM "data.dtd">
<theme_official_plugins xmlns="https://websealevel.com/wordpress/plugins/wsl_theme_dependencies">
    <theme name="atelierduboisdor">
        <plugins>
            <plugin>
                <name>ewww-image-optimizer</name>
                <label>EWWW Image Optimizer</label>
                <path>ewww-image-optimizer/ewww-image-optimizer.php</path>
                <description>Optimisation des images uploadées</description>
                <official_link>https://wordpress.org/plugins/ewww-image-optimizer/</official_link>
            </plugin>
            <plugin>
                <name>ewww-image-optimizer2</name>
                <label>EWWW Image Optimizer2</label>
                <path>ewww-image-optimizer/ewww-image-optimizer2.php</path>
                <description>Optimisation des images uploadées ++</description>
                <official_link>https://wordpress.org/plugins/ewww-image-optimizer2/</official_link>
            </plugin>
        </plugins>
    </theme>
    <theme name="foobar">
        <plugins>
            <plugin>
                <name>foo</name>
                <label>Foo</label>
                <path>foo/foo.php</path>
                <description>Affiche foo</description>
                <official_link>https://wordpress.org/plugins/ewww-image-optimizer/</official_link>
            </plugin>
        </plugins>
    </theme>
</theme_official_plugins>
